export default {
  LOAD_REQUEST: '@user/LOAD_REQUEST',
  LOAD_SUCCESS: '@user/LOAD_SUCCESS',
  LOAD_FAILURE: '@user/LOAD_FAILURE',

  UPDATE_REQUEST: '@user/UPDATE_REQUEST',
  UPDATE_SUCCESS: '@user/UPDATE_SUCCESS',
  UPDATE_FAILURE: '@user/UPDATE_FAILURE',

  REMOVE: '@user/REMOVE',
};
