export default {
  SET_REGIONS: '@filters/SET_REGIONS',
  REMOVE_REGIONS_SELECTION: '@filters/REMOVE_REGIONS_SELECTION',
  SELECT_REGION: '@filters/SELECT_REGION',

  SET_SKILLS: '@filters/SET_SKILLS',
  REMOVE_SKILLS_SELECTION: '@filters/REMOVE_SKILLS_SELECTION',
  SELECT_SKILL: '@filters/SELECT_SKILL',

  SELECT_LEVEL: '@filters/SELECT_LEVEL',
  REMOVE_SKILL_LEVELS_SELECTION: '@filters/REMOVE_SKILL_LEVELS_SELECTION',

  SET_STYLES: '@filters/SET_STYLES',
  REMOVE_STYLES_SELECTION: '@filters/REMOVE_STYLES',
  SELECT_STYLE: '@filters/SELECT_STYLE',
};
